### ISSUE TITLE
MITObim fails on iteration 0

### ISSUE THREAD

**Issue by Alexander-Stuckey** [chrishah/MITObim#10]
I have an issue with MITObim 1.8 using mira v4.0.2.
The test data works fine, but when I try run MITObim on my data  using the --quick option I get the following error: Modification of non-creatable array value attempted, subscript -1 at MITObim_1.8.pl line 818, <REF> line 11.

The full command I use to run MITObim is: perl MITObim_1.8.pl -end 50 --quick reference.fasta -sample sample -ref ref -readpool sample.fastq --paired --clean

This problem occurs when running on sata drives both on my work VM and the work cluster and when loaded into a ramdisk (~16gb space) on my work VM and ramdisk (~48gb) on the work cluster.

Regards,

Alex

**Comment by chrishah** [comment]
Sorry, I missed that one! Did you manage to sort it out?
cheers,
Christoph

**Comment by Alexander-Stuckey** [comment]
Hi Christoph

I did, the problem seemed to be that it did not like dealing with 
compressed inputs. Uncompressed inputs worked fine.

Cheers,

Alex

On 24/11/15 08:57, Christoph Hahn wrote:
>
> Sorry, I missed that one! Did you manage to sort it out?
> cheers,
> Christoph
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/chrishah/MITObim/issues/10#issuecomment-159045862>.
>

-- 
Bioinformatician
Bioinformatics Institute
The University of Auckland
