### ISSUE TITLE
Weird issue of "use: command not found"

### ISSUE THREAD

**Issue by cypridina** [chrishah/MITObim#11]
Hi,

I'm using Ubuntu 12, the latest version of MITObim (pulled 25 Aug 2015), and MIRA 4.0.2.

I'm trying to execute MITObim using `bash MITObim_1.8.pl` after making it executable with `chmod a+x MITObim_1.8.pl`

Instead of the usage being displayed, I get these errors:
```
> bash MITObim_1.8.pl
MITObim_1.8.pl: line 8: use: command not found
MITObim_1.8.pl: line 9: use: command not found
MITObim_1.8.pl: line 10: use: command not found
MITObim_1.8.pl: line 11: syntax error near unexpected token `('
MITObim_1.8.pl: line 11: `use Cwd qw(abs_path);'
```

I tried searching through the rest of the script to see where these lines might be used to no avail. Thoughts? Thank you for any insight.

**Comment by chrishah** [comment]
Hello,

The problem is that you invoke MITObim as if was a bash script. No need to add the `bash`. If anything it would be `perl MITObim`, but it isn't really needed either. Simply `MITObim_1.8.pl` should do.

Hope that helps! Good luck!

cheers,
Christoph

**Comment by cypridina** [comment]
Doh. That was a silly mistake. It's working fine now.

I was confused because in the tutorial you have `-bash-4.1$` preceding the `MITObim.pl` bit.
