### ISSUE TITLE
Mirabait fails on iteration 0

### ISSUE THREAD

**Issue by cypridina** [chrishah/MITObim#12]
Earlier today I successfully ran tutorial 3 using MITObim 1.6. I then deleted the iteration files, and tried to run the program on my own data. It failed at iteration 0.

I switch the call to replicate tutorial 3 again, and I keep getting the same error. See below. Any thoughts? Thanks for all of your help so far!
```
MITObim - mitochondrial baiting and iterative mapping
version 1.6
author: Christoph Hahn, (c) 2012-2013

quick option selected! -maf option will be ignored (if given)

Full command run: /PATH/MITObim/MITObim_1.6.pl -strain testpool -ref Tthymallus-COI 
-readpool /PATH/MITObim/testdata1/Tthymallus-150bp-300sd50-interleaved.fastq 
--quick /PATH/MITObim/testdata1/Tthymallus-COI-partial-HQ961018.fasta -end 100 
--noshow --clean

All paramters seem to make sense:
startiteration: 0
enditeration: 100
strainname: testpool
refname: Tthymallus-COI
readpool: /PATH/MITObim/testdata1/Tthymallus-150bp-300sd50-interleaved.fastq
maf: 0
quick: /PATH/MITObim/testdata1/Tthymallus-COI-partial-HQ961018.fasta
paired: 0
denovo: 0 (mapping=0, denovo=1)
noshow: 1
read trimming: 0 (off=0, on=1)
kmer baiting: 31
platform: SOLEXA
clean: 1 (off=0, on=1)
proofread: 0

Starting MITObim

==============
 ITERATION 0
==============
Aug 26 16:45:28


quick option baits reads from provided reference in iteration 0

fishing readpool using mirabait (k = 31)


mirabait seems to have failed - see detailed output above
> 
```
(returns back to command prompt here)

**Comment by cypridina** [comment]
Also, I have in no way modified the pooled fastq or the COI fasta.

**Comment by chrishah** [comment]
Hi,

Just to make sure: Are you running `MITObim_1.6.pl` on purpose? Could it be that in your earlier tests you ran version 1.8? Could you give it a quick try?

If that doesn't fix it and/or you are running 1.6 on purpose could you please rerun without the `--noshow` flag and let me know what it says.
Thanks!

cheers,
Christoph

**Comment by cypridina** [comment]
Hi Christoph,

That's right, I chose to use 1.6 and mira 3.4 to avoid using the conf file. I just ran it without --noshow with the same results (crashed on iteration 0).

I added sonfs=no to -MI: on line 289 to get around my NFS problem. It worked for tutorials 2 and 3, then it stopped working like I described on github.

I plan to remove the MITObim directory entirely from my server-side reinstall, then I'll try again.

Cool software, by the way. I hope I can get it working!

-Darrin

**Comment by chrishah** [comment]
Hi Darrin,
Hmm, I can't  really reconstruct what happened. Hope a fresh download will fix it. If not then send me the output you get if you run 1.6 without the `--noshow`. 

Btw, if at all possible I would use MITObim 1.8 with MIRA 4 - I have not really benchmarked it but the MIRA performance has improved quite a bit from 3.4 to 4. Having said that it might not matter too much for a mt genome but anyway.. So if the issue with 1.8 is just the NFS thing than you can add your `-MI:sonfs=no` also to line 878 in the 1.8 version and it should work!

Let me know how it goes!

cheers,
Christoph

**Comment by cypridina** [comment]
Hi Christoph,

A fresh download of MITObim from git fixed my problems. I must have screwed
up the code unknowingly. I have since switched to using MITObim 1.8 per
your recommendation.

I've now switched to analyzing my own data, but I'm running into some weird
problems. I have about 580,000 PE reads of 2x75 for my sample, and a COI
fragment around 600bp of a species in a closely related genus.

I keep trying to assemble the mitogenome using different kbait sizes and
different missmatch settings (ranging from 15 to 9999), but everything
converges the same 985bp fragment after 7 iterations. Do you have any idea
what might cause this and how I could change my settings/filter the reads
to get the whole mitogenome?

I'm in the Green and Shapiro group by the way -- I saw you cited some of
their papers in the MITObim paper! Your software is good for my analyses
since I'm using poorly studied invertebrates with no closely-related
published mitogenomes.

Cheers,
Darrin

(ie -kbait 20 -end 100 --missmatch 9999 --clean or -kbait 20 -end 100
--missmatch 40 --clean)

On Wed, Aug 26, 2015 at 5:57 PM, Christoph Hahn <notifications@github.com>
 wrote:

> Hi,
>
> Just to make sure: Are you running MITObim_1.6.pl <http://mitobim_1.6.pl/> on
> purpose? Could it be that in your earlier tests you ran version 1.8? Could
> you give it a quick try?
>
> If that doesn't fix it and/or you are running 1.6 on purpose could you
> please rerun without the --noshow flag and let me know what it says.
> Thanks!
>
> cheers,
> Christoph
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chrishah/MITObim/issues/12#issuecomment-135223026>.
>
>

**Comment by chrishah** [comment]
Hi Darrin,
It sounds a bit like you might have low coverage. How may reads are involved in your final contig of ~1kb length? 
There are a few things you can try:
1) try to use your ~1kb contig (as you get it from all your attempts I pretty much trust it) as bait via the `--quick` option in a run with `--denovo` and `--pair`. Leave the `--missmatch` and `--kbait` alone for the moment. Essentially you want to run the Github tutorial 3b. This way MITObim will fish out reads that get a decent match with your bait. Based on these reads it will construct a readpool that contains both members of the respective pair and will do a denovo assembly. For this your reads need to be interleaved and the read headers need to end in '/1' and '/2' so MITObim can correctly identify the read pairs.
2) If you have try to add other genes or a full mt genome from a more or less closely related reference as reference. Leave `--missmatch` alone. Per default this allows 15% mismatches per read - you don't really want to go more liberal than that. If anything try to gradually reduce the `--kbait` from 31 and see if you can improve the extension behaviour.
3) I am working on an extension of MITObim that uses protein sequences as baits. It's far from production-ready, but I could give it a try with your data if you are interested..

Let me know how it goes!
cheers,
Christoph

**Comment by cypridina** [comment]
Hi Christoph,

Once again, thanks for all the helpful pointers. At this point I don't
think I will be able to reconstruct the mitogenome with the data I have,
but would be happy for you to give it a try with your protein sequence
baits.

In response to your suggestions:

When I use a closely-related species' COI (~650bp) I get a 985bp contig of
56 reads using various settings. I get this results whether I use --pair or
not. If you try it out on Species1_COI.fasta you might get the same results.

1) I tried this by adding the '/1' and '/2' tags to the end of the headers
in my interleaved files. The interleaved fastq looked OK to me but I have
included the script I used to make the normal interleaved file, then the
script that makes the file but replaces the headers. Using these options I
got worse results than above. For one analysis I used --kbait 15 and got
these funny results:

readpool contains 262649 reads
assembly contains 4246 contig(s)
min contig length: 76 bp
max contig length: 5764 bp
avg contig length: 355 bp

2) No luck here either, using the only two published mitogenomes of animals
of the same family (Ctenophores)

3) Give it a whirl! <https://app.box.com/s/qutovk3iq1t40cmq9lbg4o7pi904aq8s>
If you're successful I would be happy to add you as an author to a future
publication using this data.

I'll keep trying a bit with this species, but I have about 30 other species
that I'm trying to reconstruct right now. I'll let you know of any
successes.

Best,
Darrin Schultz

**Comment by chrishah** [comment]
Hi,
Had a quick look at your data but I am afraid for this sample the coverage is simply too low for a straight-forward reconstruction. Will see if I can get some coding sequences at least with the other approach. Will get back to you, but will probably be a while. 
In the meantime I hope you ll have more luck with your other samples! 
Let me know how it's going!
cheers,
Christoph

**Comment by cypridina** [comment]
Hi Christoph,

Thanks for taking a look at my data. I’ve been reading others’ papers about mitogenome construction and they all have much greater coverage than me. Drat!

I’ll try again when I have some HiSeq data from these libraries. I’ll let you know of my successes (or not)!

Best,
Darrin
------------------------------------------------------
bioluminescence researcher @ MBARI
genomics grad student @ UCSC
darrin.schultz91@gmail.com

**Comment by chrishah** [comment]
Good luck! Reopen if necessary!
