### ISSUE TITLE
Basic questions

### ISSUE THREAD

**Issue by WortJohn** [chrishah/MITObim#16]
Hi ,chrishah

I am a newer for MITObim . And i have two questions below.

1、Can i use it assemble chloroplast ？
2、Which is the final sequence to assemble ?

**Comment by WortJohn** [comment]
How to understand the results below ?
Y-Robinia_pseudoacacia_chloroplast_out_AllStrains.padded.fasta
Y-Robinia_pseudoacacia_chloroplast_out_AllStrains.unpadded.fasta
Y-Robinia_pseudoacacia_chloroplast_out_Robinia_pseudoacacia_chloroplast.padded.fasta
Y-Robinia_pseudoacacia_chloroplast_out_Robinia_pseudoacacia_chloroplast.unpadded.fasta
Y-Robinia_pseudoacacia_chloroplast_out_Y.padded.fasta
Y-Robinia_pseudoacacia_chloroplast_out_Y.unpadded.fasta

**Comment by WortJohn** [comment]
Why are there other letters in file "Y-Robinia_pseudoacacia_chloroplast_out_Y.padded.fasta" and "Y-Robinia_pseudoacacia_chloroplast_out_Y.unpadded.fasta" ,such as "m、w“ ？

**Comment by chrishah** [comment]
Hi,

Sorry! Yes you can in principle and many people do!

cheers,
Christoph
