### ISSUE TITLE
Info about resume on README.md?

### ISSUE THREAD

**Issue by cypridina** [chrishah/MITObim#17]
Hi @chrishah,

I ran a `--quick` run with a seed, `--end 100`, and my mitochondrial sequence didn't converge. I deleted the files thinking I needed to restart the assembly, but then realized the `-maf` and `-start` options are probably a way to resume. If that's true, would you mind putting a little bit about how to resume/extend a run in the `README.md`? Thanks, I would really appreciate it and I think it would be useful to others too!

**Comment by cypridina** [comment]
On an interesting note, the first time I ran MITObim on this data, it didn't converge after 100 iterations and a length of around ~11kbp, but the second time I ran the same command, it converged on 77 iterations at  ~10500bp. The average depth is around 250x. Maybe I should subsample my read data?

**Comment by chrishah** [comment]
Hi,
  1. You can resume any run essentially using the approach taken in tutorial I. Say you want to resume from iteration 101, you can use the same command as before, but replace `--quick` with `--maf` and point to the maf file in the `yourproject_d_results` directory of the previous iteration (iteration 100). Add `-start 101` to the command, set `-end` to something > 101 and you should be good.

  2. Such a massive difference in performance between two runs is quite unusual. Was this with the same data? I usually recommend to downsample to ~70-100x mitochondrial coverage. Just makes the life of the assembler easier. 

If you happen to have paired end data with a bit of overlap you could merge the overlapping reads first (there is a number of programs out there that do that, e.g. flash, pear) and then only use merged reads for MITObim. This would downsample and help the assembly at the same time, but of course only if enough reads merge to get decent mt coverage just from merged reads). Might be worth a shot. Read merging is really fast.

cheers,
Christoph
