### ISSUE TITLE
wondering about the results

### ISSUE THREAD

**Issue by luoshizhi** [chrishah/MITObim#20]
Hi
I am wondering about the results.In the `testpool-Salpinus_mt_genome_d_results` folder,there are 3 padded files  and 3 unpadded files.what is the difference between these files.

testpool-Salpinus_mt_genome_out_AllStrains.unpadded.fasta
testpool-Salpinus_mt_genome_out_Salpinus_mt_genome.unpadded.fasta
testpool-Salpinus_mt_genome_out_testpool.unpadded.fasta
testpool-Salpinus_mt_genome_out_AllStrains.padded.fasta
testpool-Salpinus_mt_genome_out_Salpinus_mt_genome.padded.fasta
testpool-Salpinus_mt_genome_out_testpool.padded.fasta

Thanks

**Comment by chrishah** [comment]
Hi, 
Sorry for the delay. From the MIRA [documentation](http://mira-assembler.sourceforge.net/docs/DefinitiveGuideToMIRA.html):
'The padded versions may contain stars (*) denoting gap base positions where there was some minor evidence for additional bases, but not strong enough to be considered as a real base. Unpadded versions have these gaps removed.'

Generally you want to look at the `*unpadded*` file. Of the three unpadded files the result for your sample is in the file that ends `*_out_sample.unpadded.fasta`, where 'sample' stands for whatever you have specified for `-sample` in your original command. In case of this tutorial that was `testpool`. The file ending in whatever you had specified for the `-ref` flag, i.e. in your case `*_out_Salpinus_mt_genome.unpadded.fasta`, contains just a copy of the intitial reference provided for the particular assembly. The file ending in `*AllStrains`, is a consensus of both. Usually not relevant for MITObim users. See MIRA [documentation](http://mira-assembler.sourceforge.net/docs/DefinitiveGuideToMIRA.html) for details.

cheers,
Christoph
