### ISSUE TITLE
MITObim

### ISSUE THREAD

**Issue by reginalc** [chrishah/MITObim#21]
Hi Christoph,

I am trying to reconstruct mitochondrial genomes from IonTorrent NGS data and as I have a reference genome from to the same species I thought of using the --quick approach (output message below). Apparently, my readpool does not contain any reads with reasonable match (kmer=31), which is quite surprising considering that I’m using a reference genome of the same species. 
Then, I decided to run the two-step approach and after successfully mapping assembly with MIRA 4, I tried to run MITObim and got the below error message saying that miraconvert seems to have failed - see detailed output below. Any idea how to move forward?

Many thanks,
Regina L. Cunha

--quick option:
MITObim - mitochondrial baiting and iterative mapping
version 1.8
author: Christoph Hahn, (c) 2012-2016

quick option selected! -maf option will be ignored (if given)

./MITObim_1.8.pl -start 1 -end 30 -sample testpool -ref perna_mt_genome -readpool /home/regina/mtDNA/BZP.fastq --quick /home/regina/mtDNA/pernamtDNA.fa

All paramters seem to make sense:
startiteration: 0
enditeration: 30
sample: testpool
refname: perna_mt_genome
readpool: /home/regina/mtDNA/BZP.fastq
maf: 0
quick: /home/regina/mtDNA/pernamtDNA.fa
paired: 0 (off=0, on=1)
assembly mode: 0 (mapping=0, denovo=1)
verbose: 0 (off=0, on=1)
split: 0 (off=0, on=1)
minimum avg. coverage: 0 (off=0)
clean: 0 (off=0, on=1)
trim reads: 0 (off=0, on=1)
trim overhang: 0 (no=0, yes=1)
platform: iontorrent
kmer baiting: 31

Starting MITObim 

==============
 ITERATION 0
==============
Dec  3 13:03:32

quick option baits reads from provided reference in iteration 0

fishing readpool using mirabait (k = 31)

mirabait: No bait files defined via -b and no -L given!
Did you use the command line for the old mirabait (<= 4.0.2)?

your readpool does not contain any reads with reasonable match (k = 31) to your reference - Maybe you want to different settings or even a different reference?

2-step option:
./MITObim_1.8.pl -start 1 -end 30 -sample testpool -ref perna_mt_genome -readpool /home/regina/mtDNA/BZP.fastq -maf /home/regina/mtDNA/initial-mapping-testpool-to-perna-mt_assembly/initial-mapping-testpool-to-perna-mt_d_results/initial-mapping-testpool-to-perna-mt_out.maf

All paramters seem to make sense:
startiteration: 1
enditeration: 30
sample: testpool
refname: perna_mt_genome
readpool: /home/regina/mtDNA/BZP.fastq
maf: /home/regina/mtDNA/initial-mapping-testpool-to-perna-mt_assembly/initial-mapping-testpool-to-perna-mt_d_results/initial-mapping-testpool-to-perna-mt_out.maf
quick: 0
paired: 0 (off=0, on=1)
assembly mode: 0 (mapping=0, denovo=1)
verbose: 0 (off=0, on=1)
split: 0 (off=0, on=1)
minimum avg. coverage: 0 (off=0)
clean: 0 (off=0, on=1)
trim reads: 0 (off=0, on=1)
trim overhang: 0 (no=0, yes=1)
platform: iontorrent
kmer baiting: 31

Starting MITObim 

==============
 ITERATION 1
==============
Dec  3 13:19:02

recover backbone by running miraconvert on maf file

ConvPro::checkTypes: Unknown or illegal file type 'tmp' defined as <totype>
miraconvert	(MIRALIB version 4.9.5_2 )
 Author:  Bastien Chevreux	(bach@chevreux.org)
 Purpose: convert assembly and sequencing file types.
 
 Usage: [......]
miraconvert seems to have failed - see detailed output above

**Comment by chrishah** [comment]
The issue has been picked up on the mailing list [here](https://groups.google.com/forum/#!topic/mitobim-users/tGmtKEfk8Zg) and [here](https://groups.google.com/forum/#!topic/mitobim-users/hZcsa_c29KU). Closing this.
