### ISSUE TITLE
How can i calculate the average coverage of my mitogenome assembled by MITOBim

### ISSUE THREAD

**Issue by Farheena1** [chrishah/MITObim#32]
Hi guys,
I assembled mt genome by using MITOBim, i got assembled results in fasta format, How can i calculate the average coverage (X), any tool? The tools i founded need Bam file as input.

**Comment by chrishah** [comment]
Hi,

MIRA produces some info for each assembly that it does, including averarge coverage for each contig. Say you wanted the stats for the contigs produced by the 14th iteration look into the file
 `iteration14/yoursample-yourref_assembly/yoursample-yourref_d_info/yoursample-yourref_info_contigstats.txt`. If you want bam, you can of course also just take the reads from a given iteration (e.g. `iteration14/yoursample-readpool-it14.fastq`) and map them back to your result with your favourite tool (bwa, bowtie2, whatever) and extract the mapping result as bam.  Hope that helps!
cheers,
Christoph
