### ISSUE TITLE
problem running MITObim due to miraconvert

### ISSUE THREAD

**Issue by jullee** [chrishah/MITObim#33]
Hi I am trying to run MITObim after running MIRA. However, the program is failing due to an issue with miraconvert. It gives the error:

ConvPro::checkTypes: Unknown or illegal file type 'tmp' defined as <totype>

/Linux/mira_4.9.5/bin/miraconvert -f maf -t fasta -A "SOLEXA_SETTINGS -CO:fnicpst=yes" /SciBorg/array0/lee-yaw/sunflower_organellar_genomes/MITObim/test_assembly_annuus_assembly/test_assembly_annuus_d_results/test_assembly_annuus_out.maf tmp

And then:
miraconvert seems to have failed - see detailed output above

Full log file attached. I'm running Mira 4.9.5 and MITObim 1.9.1 on a server. The only other thing of note is that I had to suppress warnings in Mira re: running mira on NSF mounted directories. (I tried redirecting the tmp dir with -DI:trt=/tmp as a parameter in the manifest file but got the same issue with miraconvert 
[log.txt](https://github.com/chrishah/MITObim/files/2484937/log.txt)

downstream when running MITObim)

**Comment by jullee** [comment]
Op just saw that there is a google group for mitobim and that Mira 4.9.5 isn't compatible with MITObim 1.9.1. I'll try mira 4.0

**Comment by MarceMora05** [comment]
Hello, I had the same problem, how was it solved?
