### ISSUE TITLE
CPU Multi threading

### ISSUE THREAD

**Issue by Vict0rC** [chrishah/MITObim#34]
Hello,
would it be possible, in later releases, to include cpu multi-thread computing? For now it works just with one core and its pity... I have hundred cores doing nothing :-(
Well thanks for your work!
Victor

**Comment by chrishah** [comment]
Hi Victor,

Thanks for your interest into MITObim! You are right, of course! Efficient parallelization is one of the goals for future releases. stay tuned!
cheers,
Christoph

**Comment by Vict0rC** [comment]
Thank you very much!
ViC
