### ISSUE TITLE
Failed to run the program

### ISSUE THREAD

**Issue by bioramg** [chrishah/MITObim#49]
Hi,
I am trying to extend my contig using Illumina reads, But its failure to run the program. Could you please check and suggest me?

MITObim - mitochondrial baiting and iterative mapping
version 1.9.1
author: Christoph Hahn, (c) 2012-2018

quick option selected! -maf option will be ignored (if given)

Full command run:
./../../anaconda3/MITObim-master/MITObim.pl -end 200 -sample mito -ref mitobim_iter_1 -readpool ./../PE_Illu_reads.fastq.gz --pair --mirapath ./../bin/mira --clean --quick ./../mt_plant.fa

All paramters seem to make sense:
startiteration: 0
enditeration: 200
sample: cke_mito
refname: mitobim_iter_111
readpool: /home/PE_Illu_reads.fastq.gz
maf: 0
quick: /home/mt_plant.fa
paired: 1 (off=0, on=1)
assembly mode: 0 (mapping=0, denovo=1)
verbose: 0 (off=0, on=1)
split: 0 (off=0, on=1)
minimum avg. coverage: 0 (off=0)
minimum contig length: 0 (off=0)
clean: 1 (off=0, on=1)
trim reads: 0 (off=0, on=1)
trim overhang: 0 (no=0, yes=1)
platform: solexa
kmer baiting: 31
number of mismatches in mapping assembly: default (15% of average read length loaded)
proofreading: off

Starting MITObim

==============
 ITERATION 0
==============
Nov  6 13:58:47

quick option baits reads from provided reference in iteration 0

reference is too long for mirabait to be handled in one go -> will be split into sub-sequences

fishing readpool using mirabait (k = 31)

mirabait: loadlocale.c:130: _nl_intern_locale_data: Assertion `cnt < (sizeof (_nl_value_type_LC_TIME) / sizeof (_nl_value_type_LC_TIME[0]))' failed.

your readpool does not contain any reads with reasonable match (k = 31) to your reference - Maybe you ll want to try different settings or even a different reference?

**Comment by travc** [comment]
@bioramg Did you resolve this?  I'm having the same issue.

**Comment by athenasyarifa** [comment]
Does anyone know the solution to this problem? I am having the same error.

**Comment by travc** [comment]
@athenasyarifa I just put `LC_ALL=C` at the front of my `MITObim.pl` command line...
```
LC_ALL=C MITObim.pl  -start 1 -end 10 -sample ...
```

That worked for me, but one of these links might give you a better solution.
https://askubuntu.com/questions/1081901/what-is-the-correct-way-to-fix-an-assertion-in-loadlocale-c
https://unix.stackexchange.com/questions/444102/loadlocale-c-nl-intern-locale-data-assertion-error

**Comment by athenasyarifa** [comment]
Thank you very much for your help! It is running now, and I will see how it goes.
