### ISSUE TITLE
-DI:trt

### ISSUE THREAD

**Issue by wendysphillips** [chrishah/MITObim#5]
Help? I would love to use MITObim. Unfortunately I work on a NFS mount. I have been able to run mira using -DI:trt=/data in the parameters line of the manifest. However, since MITObim doesn't seem to use a manifest file, I don't know how to use the -DI:trt=/data option in the MITObim call. Can you give me direction? Thanks! -Wendy

**Comment by cypridina** [comment]
I ran into this same problem today since I use a NFS-mounted data server. Maybe it would make sense to add an option to the MITObim param call to add this into the mira call? Then you wouldn't have to make a customized MITObim.pl file for everyone with the same problem! Thanks!

**Comment by chrishah** [comment]
Hi,
I've just added a new option `--redirect_tmp` to the latest version that should fix this!
Thanks!
Christoph
