### ISSUE TITLE
Reported contig length and actual contig length do not match

### ISSUE THREAD

**Issue by LeviDettwyler** [chrishah/MITObim#8]
I've been doing some runs in MITObim 1.6 and have been getting some unexpected results. In one such run, I provided a seed of 23282 bp and, at iteration 171, the program reported a contig length of 74125 bp, but an examination of the resultant _out.unpadded.fasta file shows a contig only 37080 bp. Am I misunderstanding something about the program's output? What does the "contig length" number reported by the program at each iteration correspond to? Thanks.

**Comment by chrishah** [comment]
Dear Levi,
Thanks for reporting this strange behaviour!
The contig length that MITObim reports is read directly from one of info files that the MIRA assembler provides. An extension from 23kb to 37kb sounds much more reasonable. Not sure what could have gone wrong there..
Could you look into the file `your-project_assembly/your-project_d_info/your-project_info_contigstats.txt`? The length reported by MITObim should correspond to the number in column 4 in the file, i.e. the contig length reported by MIRA. What does it say in this file? 
cheers,
Christoph

**Comment by LeviDettwyler** [comment]
Hi Christoph,

I figured out the issue! The method I was using to get the contig length in the resulting fasta file was incorrect. I just did a sanity check and looked at the file size and it's very close to the reported contig size. Thanks for your attention anyways though!
