### ISSUE TITLE
MITObim reference seqeunce

### ISSUE THREAD

**Issue by ascendo** [chrishah/MITObim#9]
Hi!

I try to use MITObim for my mitochondria genome.

Is it possible to use multiple reference genome?

My genome fastq file is almost 200G. is it possible to use it?

Thank you.

Won

**Comment by chrishah** [comment]
Hi Won,

MITObim has initially been developed and tested for single references, but It is possible to use MITObim with several references - just put them all into a fasta file and specify it as reference via the --quick option. In theory you can go directly for your 200G file, but there may be a few issues:
- MITObim will search through your 200G of data in each iteration to find reads that match the bait. This will result in quite long runtime.
- With 200G of data the coverage of your mt genome will most likely be enormous, which will worsen the signal-to-noise ratio and complicate assembly. Very high coverage will also result in increased memory requirements. In general a coverage of ~50-100x would be ideal for assembly.

My advice would therefore be to down-sample your data. Take e.g. 10M random reads feed them into MITObim and see what happens. You should get your results very quickly and if needed you can just increase your sample size. Also you might run a couple of analyses with different random subsamples to see how consistent your results are.

Hope that helps!

cheers,
Christoph

**Comment by ascendo** [comment]
Thank you for your help.

I reduced my fastq file to 1Gb. And it looks it will take forever.

Is there anyway to use multithread in Mira?

Thank you.

**Comment by chrishah** [comment]
Hi,

MIRA will automatically determine the number of cores available and use multiple threads if possible. But not all steps in a MIRA assembly can be multithreaded.

1 Gb of data does not sound a lot but if your coverage is very high the assembly might still take a while. How long do your iterations take? 

cheers,
Christoph

**Comment by chrishah** [comment]
Guess this is sorted then - Reopen if necessary!

**Comment by sghignone** [comment]
Hi Christoph,
I have a question related to multi-threading. I'm working on fungal genome supposed to be larger than 800MB. Yes, it's huge. Previous works have already sequenced the mitochondrial genome, but it was made with 454, and we have doubts it's non correctly assembled. Now, I have this paired-end library we used for the assembly, and I wanted to use it starting with the COI example from the tutorial. 

When using the suggested command:
```
-bash-4.1$ ~/PATH/TO/MITObim.pl -sample testpool -ref Tthymallus-COI -readpool ~/PATH/TO/testdata1/Tthymallus-150bp-300sd50-interleaved.fastq --quick ~/PATH/TO/testdata1/Tthymallus-COI-partial-HQ961018.fasta -end 50 --denovo --paired --clean &> log
```
the program exits with this warning

```
-------- MEDIUM warning --------
 
 MIRA warncode: ASCOV_VERY_HIGH
 Title: Very high average coverage
 
 You are running a genome de-novo assembly and the current best estimation for
 average coverage is 644x (note that this number can be +/- 20% off the real
 value). This is a pretty high coverage,higher than the current warning threshold
 of 80x.
 
 You should try to get the average coverage not higher than, say, 60x to 100x for
 Illumina data or 40x to 60x for 454 and Ion Torrent data. Hybrid assemblies
 should target a total coverage of 80x to 100x as upper bound. For that, please
 downsample your input data.
 
 This warning has two major reasons:
 - for MIRA and other overlap based assemblers, the runtime and memory
   requirements for ultra-high coverage projects grow exponentially, so reducing
   the data helps you there
 - for all assemblers, the contiguity of an assembly can also suffer if the
   coverage is too high, i.e. you get more contigs than you would otherwise.
   Causes for this effect can be non-random sequencing errors or low frequency
   sub-populations with SNPs which become strong enough to be mistaken for
   possible repeats.
 A coverage of >300x ... no really, are you kidding me? *sigh*
 With the coverage you currently have, you *really* should downsample your data.
 You. Have. Been. Warned!
[...]
```
It's a pity, because the library is really good ,and I don't feel like reducing it.
On the other hand, using the other example:
```
-bash-1.4$ ~/PATH/TO/MITObim.pl -sample testpool -ref Tthymallus-COI -readpool ~/PATH/TO/testdata1/Tthymallus-150bp-300sd50-interleaved.fastq --quick ~/PATH/TO/testdata1/Tthymallus-COI-partial-HQ961018.fasta -end 100 --clean &> log
```
the program works well, using ONE only CPU (1 over 59 available....)
Can you briefly explain the reasons of this behaviour and whether there is the possibility to push mirabait in multi-threading?
Thanks a lot in advance.
Regards,
stefano
